### ISSUE TITLE
The number of images and reports are not correct

### ISSUE THREAD

**Issue by caodoanh2001** [zhjohnchan/R2Gen#1]
Hi, thank you for the paper.

However, when I download the IU X-Ray dataset you provided, the number of images is not correct as you reported in the paper.
In detail, there are only 6091 images, and 2069, 296, 590 reports for training, validation and testing sets, respectively.

Can you check again?

Thank you very much.

**Comment by XYers** [comment]
Hi , @caodoanh2001 ,did you just use the download link on this site?Because I have tried to download from this page,but from the  link to google cloud,the download process will report an error,I wonder if you face the same problem.

**Comment by caodoanh2001** [comment]
Hi Friend, 
I downloaded the dataset via this link: https://drive.google.com/file/d/1c0BXEuDy8Cmm2jfN0YYGkQxFZd2ZIoLg/view?usp=sharing

but the number of images in train, valid and test set is not correct as the paper.

**Comment by o0t1ng0o** [comment]
@caodoanh2001 @zhjohnchan 
I also found that the number of samples is not correct. 
Or did the author remove the invalid samples?

IU-xray
train : 2069
val: 296
test: 590

Mimic-xray
train: 270790
val : 2130
test: 3858

**Comment by zhjohnchan** [comment]
Hi,

Thanks for your attention!

In both datasets, there are some studies without images or findings. We preprocessed the datasets by filtering them.

Best,
Zhihong
