### ISSUE TITLE
Visualization of Captions

### ISSUE THREAD

**Issue by jainnipun11** [zhjohnchan/R2Gen#2]
Hey, I followed the steps you have mentioned but I couldn't visualize the captions generated. I took IU_Xray dataset. Kindly guide me. Thank you.

**Comment by XYers** [comment]
Of course,you should use the MIMIC_CXR dataset instead.

**Comment by dzldzldzl** [comment]
Hey,I followed the steps you too,andI took mimic_cer dataset.but,I couldn't visualize the captions generated,when test and plot， none of them can be achieved, and no results can be seen, and if you have more time, I would like to get your help

**Comment by jainnipun11** [comment]
Hey @dzldzldzl @XYers, do you know how to run the model only on Base without RM and MCLN? I tried various thing but doesn't seem to work.

Thanks,
Nipun Jain

**Comment by FJYfxt** [comment]
> Hey,I followed the steps you too,andI took mimic_cer dataset.but,I couldn't visualize the captions generated,when test and plot， none of them can be achieved, and no results can be seen, and if you have more time, I would like to get your help

**Comment by zhjohnchan** [comment]
Hi all,

Please follow [this](https://github.com/zhjohnchan/R2Gen#visualization) to visualize both the generated captions and attention maps.

Best,
Zhihong
