### ISSUE TITLE
Impression or Finding section

### ISSUE THREAD

**Issue by ChantalMP** [zhjohnchan/R2Gen#4]
Hi, thanks for your work and for publishing your code!
One question, for the MIMIC-CXR dataset, do you predict the impression section, the finding section or concatenate both?
Thanks a lot in advance,
Chantal

**Comment by zhjohnchan** [comment]
Hi Chantal,

Thanks for your attention. We predict the findings section only.

All the best,
Zhihong

**Comment by ChantalMP** [comment]
Thank you very much! :)
